# Library Load


## @knitr libraryLoad
# library(gt)
library(chron)
library(readr)
library(readxl)
library(tidyxl)
library(unpivotr)
library(tidyverse)
library(sf)
library(mapview)
library(tncThemes)
library(hrbrthemes)
library(leaflet)
library(knitr)
library(crosstalk)
library(htmlwidgets)
library(htmltools)
library(magrittr)
library(readxl)
library(writexl)
library(rpivotTable)
library(directlabels)
library(DataExplorer)
library(DT)
# library(arcgisbinding, quietly = TRUE)
library(datapasta)
library(kableExtra)
library(ggimage)
library(magick)
library(patchwork)
library(tmap)
library(tmaptools)
library(rmarkdown)
library(pagedown)
